apiVersion: apps/v1
kind: Deployment
metadata:
  name: chord-be-workers
  labels:
    app: chord-be-workers
  namespace: chord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chord-be-workers
  template:
    metadata:
      labels:
        app: chord-be-workers
      annotations:
        restartedAt: '2006-01-02T15:04:05Z07:00'
      namespace: chord
    spec:
      containers:
      - name: chord-be-workers
        image: pw1124/chord-be-workers:${LATEST_WORKERS_IMAGE}
        envFrom:
        - configMapRef:
            name: chord-be-common-cm
        - configMapRef:
            name: chord-be-workers-cm
        - secretRef:
            name: chord-be-common-secrets
        - secretRef:
            name: chord-be-workers-secrets
        volumeMounts:
        - mountPath: /shared
          name: cache-volume
      initContainers:
      - name: youtube-dl-bin
        image: pw1124/youtube-dl-bin:${LATEST_YOUTUBE_IMAGE}
       # tty: true
        volumeMounts:
        - mountPath: /youtube-dl
          name: cache-volume
        command: ["/bin/sh"]
        args: ["-c", "mv /home/youtube-dl /youtube-dl/"]
#      nodeSelector:
#        ram: 8gb
      volumes:
      - name: cache-volume
        emptyDir: {}
      imagePullSecrets:
      - name: regcred

# to create `regcred`, you need a dockerhub account,
# and then run: `kubectl create secret generic regcred \
#                  --from-file=.dockerconfigjson=[path/to/.docker/config.json] \
#                  --type=kubernetes.io/dockerconfigjson`
#
# you can then inspect it by: `kubectl get secret regcred \
#                                --output="jsonpath={.data.\.dockerconfigjson}" | base64 –decode

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: chord-be-workers-cm
  namespace: chord
data:
  SPLEETER_BIN_PATH: /usr/local/bin/spleeter
  SPLEETER_WORKING_DIR_PATH: /spleeter-scratch
  YOUTUBEDL_BIN_PATH: /shared/youtube-dl
  YOUTUBEDL_WORKING_DIR_PATH: /youtubedl-scratch
  GOOGLE_CLOUD_STORAGE_BUCKET_NAME: chord-paper-tracks
  RABBITMQ_QUEUE_NAME: chord-paper-tracks
  DEMUCS_BIN_PATH: /usr/local/bin/demucs
  DEMUCS_WORKING_DIR_PATH: /demucs-scratch
