apiVersion: apps/v1
kind: Deployment
metadata:
  name: chord-be
  labels:
    app: chord-be
spec:
  replicas: 6
  selector:
    matchLabels:
      app: chord-be
  template:
    metadata:
      labels:
        app: chord-be
      annotations:
        restartedAt: ""
    spec:
      containers:
      - name: chord-be
        image: pw1124/chord-be:latest
        env: 
        - name: ALLOWED_FE_ORIGINS
          valueFrom:
            secretKeyRef:
              name: cors-origin
              key: url
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred

# note: for CORS_ORIGIN environment variable, a local k8s secret needs to be created.
