apiVersion: apps/v1
kind: Deployment
metadata:
  name: chord-be-workers
  labels:
    app: chord-be-workers
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: chord-be-workers
  template:
    metadata:
      labels:
        app: chord-be-workers
      annotations:
        restartedAt: '2006-01-02T15:04:05Z07:00'
    spec:
      containers:
      - name: chord-be-workers
        image: pw1124/chord-be-workers:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /shared
          name: cache-volume
      initContainers:
      - name: youtube-dl-bin
        image: pw1124/youtube-dl-bin:latest
       # tty: true
        volumeMounts:
        - mountPath: /youtube-dl
          name: cache-volume
        command: ["/bin/sh"]
        args: ["-c", "mv /home/youtube-dl /youtube-dl/"]
      volumes:
      - name: cache-volume
        emptyDir: {}
      imagePullSecrets:
      - name: regcred

# to create `regcred`, you need a dockerhub account,
# and then run: `kubectl create secret generic regcred \
#                  --from-file=.dockerconfigjson=[path/to/.docker/config.json] \
#                  --type=kubernetes.io/dockerconfigjson`
#
# you can then inspect it by: `kubectl get secret regcred \
#                                --output="jsonpath={.data.\.dockerconfigjson}" | base64 –decode
