apiVersion: apps/v1
kind: Deployment
metadata:
  name: chord-be
  labels:
    app: chord-be
spec:
  replicas: 6
  selector:
    matchLabels:
      app: chord-be
  template:
    metadata:
      labels:
        app: chord-be
      annotations:
        restartedAt: ""
    spec:
      containers:
      - name: chord-be
        image: pw1124/chord-be:latest
        env:
        - name: RUST_LOG
          value: "info"
        - name: ENVIRONMENT
          value: "production"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-dynamodb
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-dynamodb
              key: secret_access_key
        - name: ALLOWED_FE_ORIGINS
          valueFrom:
            secretKeyRef:
              name: cors-origin
              key: url
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: regcred

# note: for secretKeyRefs, you have to create the secret in your k8s cluster.
