FROM debian:bookworm

ENV PATH="/.venv/bin:/usr/local/go/bin:$PATH"

RUN apt-get update && \
    apt-get install -y \
      python3.11 \
      python3.11-venv \
      python3-pip \
      python-is-python3 \
      build-essential \
      ffmpeg \
      curl

RUN python -m venv .venv

RUN pip install --no-cache-dir spleeter==2.4.2
RUN pip install --no-cache-dir demucs==4.0.1

RUN curl -sLO https://go.dev/dl/go1.18.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.18.linux-amd64.tar.gz && \
    rm go1.18.linux-amd64.tar.gz

RUN rm -rf /var/lib/apt/lists/*
