# note: for secretKeyRefs, you have to create the secret in your k8s cluster.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chord-be
  labels:
    app: chord-be
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chord-be
  template:
    metadata:
      labels:
        app: chord-be
      annotations:
        restartedAt: ""
    spec:
      containers:
      - name: chord-be
        image: pw1124/chord-be:${LATEST_IMAGE}
        envFrom:
        - configMapRef:
            name: chord-be-common-cm
        - configMapRef:
            name: chord-be-cm
        - secretRef:
            name: chord-be-common-secrets
        - secretRef:
            name: chord-be-secrets
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: chord-be-cm
data:
  # currently nothing here yet
