name: PR Gate

on:
  pull_request:
    branches: [ master ]

jobs:
  server-build-and-test:
    name: Server Gates
    uses: ./.github/workflows/server-build-and-test.yml

  worker-build-and-test:
    name: Worker Gates
    uses: ./.github/workflows/worker-build-and-test.yml
