name: PR Gate

on:
  pull_request:
    branches: [ master ]

jobs:
  server-build-and-test:
    name: Server Checks
    uses: ./.github/workflows/server-build-and-test.yml

  worker-build-and-test:
    name: Worker Checks
    uses: ./.github/workflows/worker-build-and-test.yml
