name: Actions Runner Tester
on:
  workflow_dispatch:

jobs:
  test-runners:
    runs-on: arc-chord-be-runner-set
    steps:
    - name: "🎉 It's running! 💦💦"
      run: echo "🎉 arc-chord-be-runner-set running!! 💦💦"
    - name: kubectl test
      uses: steebchen/kubectl@master
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: v1.32.2
        command: version
#    - name: where is which?
#      run: which kubectl
#    - name: kubectl test
#      uses: actions-hub/kubectl@master
#      env:
#        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
#      with:
#        args: version
