name: Worker Deploy to Production

on:
  push:
    branches:
      - master
    paths:
      - 'worker/**'

jobs:
  worker-build-and-test:
    name: Worker Gates
    uses: ./.github/workflows/worker-build-and-test.yml


  push:
    name: Build Image and Deploy
    runs-on: cluster-runner
    steps:
      # Checkout with history (to get git describe output properly)
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Run script, updates the GIT-VERSION-FILE with version number
      - name: Update GIT-VERSION-FILE
        run: bash git-version.sh
      - name: Get version tag from GIT-VERSION-FILE
        run: echo "gitver=$(cat GIT-VERSION-FILE)" >> $GITHUB_ENV
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # base image

      - name: Build image w/version
        run: docker build . --file ./worker/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/chord-be-workers:${{ env.gitver }}
      - name: Push image w/version
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/chord-be-workers:${{ env.gitver }}

      # youtube-dl

      - name: Build youtube-dl image w/version
        run: docker build --no-cache ./worker/youtube-dl --tag ${{ secrets.DOCKERHUB_USERNAME }}/youtube-dl-bin:${{ env.gitver }}
      - name: Push youtube-dl image w/version
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/youtube-dl-bin:${{ env.gitver }}

      - name: Deploy Project to K8S Cluster
        uses: steebchen/kubectl@master
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.24.3
          command: set image --record deploy/chord-be-workers chord-be-workers=${{ secrets.DOCKERHUB_USERNAME }}/chord-be-workers:${{ env.gitver }}

      - name: Verify K8S Deployment
        uses: steebchen/kubectl@master
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.24.3
          command: rollout status deploy/chord-be-workers

      - name: Cleanup Images
        run: docker image prune -af
