name: Worker Build/Test

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: cluster-runner
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true

      - name: Build
        working-directory: ./src/worker
        run: go build -v worker.go

  test:
    name: Test
    runs-on: cluster-runner

    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000

      rabbitmq:
        image: rabbitmq:3.10
        ports:
          - 5672:5672

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true

      - name: Test
        working-directory: ./src/worker
        run: go test -v ./...
        